spring:
  profiles:
    # 이후 배포 시 dev & prod로 변경
    active: local

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  access-token-validity: 3600000  # 1시간
  refresh-token-validity: 604800000  # 7일