import Navbar from "@/components/NavBar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "몽글몽글",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body>
        {children}
        <Navbar />
      </body>
    </html>
  );
}
