import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider } from "@/context/ThemeContext";
import { Provider } from "react-redux";
import { store } from "@/store/store";
import Header from "@/components/header/orgamisms/Header";
import ClientLayout from "@/components/layout/ClientLayout";
import Navbar from "@/components/navbar/organisms/NavBar";

export const metadata: Metadata = {
  title: "몽글몽글",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-theme-50 flex flex-col items-center">
        <ClientLayout>
          <ThemeProvider initialTheme="sky" initialFont="suit">
            <Header />
            <main className="flex w-full md:w-3/4 lg:w-1/2 mx-auto min-h-screen p-4">
              {children}
            </main>
            <Navbar />
          </ThemeProvider>
        </ClientLayout>
      </body>
    </html>
  );
}
