import "./globals.css";

import Navbar from "@/components/NavBar";
import { ThemeProvider } from "@/context/ThemeContext";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "몽글몽글",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-theme-50">
        <ThemeProvider initialTheme="sky">
          {children}
          <Navbar />
        </ThemeProvider>
      </body>
    </html>
  );
}
